version: "3.7"

services:
  t-blog-api-gateway:
    image: nginx:1.21.6
    container_name: t-blog-api-gateway
    depends_on:
      - t-auth-service
      - t-user-service
      - t-blog-service
      - t-article-service
      - t-comment-service
    volumes:
      - ./t-blog-api-gateway/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80

  t-user-service:
    image: t-user-service
    container_name: t-user-service
    build: ./t-user-service
    volumes:
      - ./t-user-service:/app/
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${USER_SERVICE_POSTGRES_DB}
      - AUTH_SECRET_KEY=${AUTH_SECRET_KEY}
      - AUTH_TOKEN_ALGORITHM=${AUTH_TOKEN_ALGORITHM}
      - AUTH_ACCESS_TOKEN_EXPIRE_MINUTES=${AUTH_ACCESS_TOKEN_EXPIRE_MINUTES}

  t-blog-service:
    image: t-blog-service
    container_name: t-blog-service
    build: ./t-blog-service
    volumes:
      - ./t-blog-service:/app/
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${BLOG_SERVICE_POSTGRES_DB}
      - USER_SERVICE_HOST_URL=${USER_SERVICE_HOST_URL}

  t-article-service:
    image: t-article-service
    container_name: t-article-service
    build: ./t-article-service
    volumes:
      - ./t-article-service:/app/
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${ARTICLE_SERVICE_POSTGRES_DB}
      - USER_SERVICE_HOST_URL=${USER_SERVICE_HOST_URL}
      - BLOG_SERVICE_HOST_URL=${BLOG_SERVICE_HOST_URL}

  t-comment-service:
    image: t-comment-service
    container_name: t-comment-service
    build: ./t-comment-service
    volumes:
      - ./t-comment-service:/app/
    environment:
      - DATABASE_URL=postgresql://${DB_USER}:${DB_PASSWORD}@${DB_HOSTNAME}/${COMMENT_SERVICE_POSTGRES_DB}
      - USER_SERVICE_HOST_URL=${USER_SERVICE_HOST_URL}
      - ARTICLE_SERVICE_HOST_URL=${ARTICLE_SERVICE_HOST_URL}
