# This workflow will build and push the image of the t-blog-service to Google Container Registry and deploy it to Google Cloud Run
# on push or pull request to the main branch if there are changes in the t-blog-service folder.

name: Deploy t-blog-service to Google Cloud Run
on:
  push:
    branches:
      - main
    paths:
      - "t-blog-service/**"
jobs:
  deploy:
    name: Deploying t-blog-service
    runs-on: ubuntu-latest
    environment: t-blog-service-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0.7.3
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY_JSON }}

      # Build and push image to Google Container Registry
      - name: Building the Docker Image (🏗)
        working-directory: ./t-blog-service
        run: gcloud builds submit --tag gcr.io/t-blog-bg/t-blog-service:latest

      - name: Deploy to Cloud Run (🚀)
        uses: google-github-actions/deploy-cloudrun@v0.10.0
        with:
          service: t-blog-service
          image: gcr.io/t-blog-bg/t-blog-service:latest
          region: europe-west1
          env_vars: |
            DATABASE_URL=postgresql://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@${{ secrets.DB_HOSTNAME }}/${{ secrets.BLOG_SERVICE_POSTGRES_DB }}
            USER_SERVICE_HOST_URL=${{ secrets.USER_SERVICE_HOST_URL }}
            RABBITMQ_URL=${{ secrets.RABBITMQ_URL }}
